server:
  port:
    9092
  error:
    whitelabel:
       enabled:
          false  

---
# spring:
#     datasource:
#         driver-class-name: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
#         username: ${DB_USERNAME}
#         password: ${DB_PASSWORD}
#         hikari:
#             initialization-fail-timeout: 0        
#     jpa:
#         generate-ddl: true
#         show-sql: true
#         hibernate:
#             ddl-auto: update
#     mvc:
#       view:
#          prefix: /WEB-INF/jsp/
#          suffix: .jsp
           
